// =====================================================================
// DnDCast — editor.js
// Admin editor for scenes, sessions, and campaigns.
// =====================================================================

// === State ============================================================

let editorScenes    = [];
let editorSessions  = [];
let editorCampaigns = [];
let dirHandle       = null; // FSA directory handle (Chrome/Edge)
let isDirty         = false;

let editingSceneIdx    = null; // null = new item
let editingSessionIdx  = null;
let editingCampaignIdx = null;
let editingSessionScenes = []; // working copy of session.scenes during edit
let idAutoGenerated = true;    // tracks whether scene/session ID was auto-slugified

// === DOM ==============================================================

const $ = id => document.getElementById(id);

const openBtn          = $('open-btn');
const saveBtn          = $('save-btn');
const statusBar        = $('status-bar');
const tabBtns          = document.querySelectorAll('.tab-btn');
const tabPanels        = document.querySelectorAll('.tab-panel');

// Scenes
const addSceneBtn      = $('add-scene-btn');
const scenesList       = $('scenes-list');
const scenesEmpty      = $('scenes-empty');
const sceneEditPanel   = $('scene-edit-panel');
const sceneEditHeading = $('scene-edit-heading');
const sceneForm        = $('scene-form');
const deleteSceneBtn   = $('delete-scene-btn');

// Sessions
const addSessionBtn        = $('add-session-btn');
const sessionsList         = $('sessions-list');
const sessionsEmpty        = $('sessions-empty');
const sessionEditPanel     = $('session-edit-panel');
const sessionEditHeading   = $('session-edit-heading');
const sessionForm          = $('session-form');
const deleteSessionBtn     = $('delete-session-btn');
const sessionCampaignSelect= $('session-campaign-select');
const sessionSceneList     = $('session-scene-list');
const sessionSceneEmpty    = $('session-scene-empty');
const addSceneSelect       = $('add-scene-select');
const addSceneToSessionBtn = $('add-scene-to-session-btn');

// Campaigns
const addCampaignBtn      = $('add-campaign-btn');
const campaignsList       = $('campaigns-list');
const campaignsEmpty      = $('campaigns-empty');
const campaignEditPanel   = $('campaign-edit-panel');
const campaignEditHeading = $('campaign-edit-heading');
const campaignForm        = $('campaign-form');
const deleteCampaignBtn   = $('delete-campaign-btn');

// Modal (file input fallback)
const openModal        = $('open-modal');
const openConfirmBtn   = $('open-confirm-btn');
const openCancelBtn    = $('open-cancel-btn');
const scenesFileInput  = $('scenes-file-input');
const sessionsFileInput= $('sessions-file-input');
const campaignsFileInput=$('campaigns-file-input');

// === Init =============================================================

function init() {
  // Tab switching
  tabBtns.forEach(btn => btn.addEventListener('click', () => switchTab(btn.dataset.tab)));

  // Header actions
  openBtn.addEventListener('click', openProject);
  saveBtn.addEventListener('click', saveProject);

  // Scene tab
  addSceneBtn.addEventListener('click', () => openSceneEdit(null));
  sceneForm.addEventListener('submit', e => { e.preventDefault(); saveScene(); });
  deleteSceneBtn.addEventListener('click', deleteScene);

  // Auto-slugify scene title → id
  const sceneTitle = sceneForm.querySelector('[name="title"]');
  const sceneId    = sceneForm.querySelector('[name="id"]');
  sceneTitle.addEventListener('input', () => {
    if (idAutoGenerated) sceneId.value = slugify(sceneTitle.value);
  });
  sceneId.addEventListener('input', () => { idAutoGenerated = false; });

  // Session tab
  addSessionBtn.addEventListener('click', () => openSessionEdit(null));
  sessionForm.addEventListener('submit', e => { e.preventDefault(); saveSession(); });
  deleteSessionBtn.addEventListener('click', deleteSession);
  addSceneToSessionBtn.addEventListener('click', addSceneToSession);

  // Auto-slugify session title → id
  const sessionTitle = sessionForm.querySelector('[name="title"]');
  const sessionId    = sessionForm.querySelector('[name="id"]');
  sessionTitle.addEventListener('input', () => {
    if (idAutoGenerated) sessionId.value = slugify(sessionTitle.value);
  });
  sessionId.addEventListener('input', () => { idAutoGenerated = false; });

  // Campaign tab
  addCampaignBtn.addEventListener('click', () => openCampaignEdit(null));
  campaignForm.addEventListener('submit', e => { e.preventDefault(); saveCampaign(); });
  deleteCampaignBtn.addEventListener('click', deleteCampaign);

  // Auto-slugify campaign title → id
  const campaignTitle = campaignForm.querySelector('[name="title"]');
  const campaignId    = campaignForm.querySelector('[name="id"]');
  campaignTitle.addEventListener('input', () => {
    if (idAutoGenerated) campaignId.value = slugify(campaignTitle.value);
  });
  campaignId.addEventListener('input', () => { idAutoGenerated = false; });

  // Close-edit buttons (close panel without saving)
  document.querySelectorAll('.close-edit-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const panelId = btn.dataset.panel;
      if (panelId) $(panelId).hidden = true;
    });
  });

  // Browse buttons
  const canBrowse = 'showOpenFilePicker' in window;
  document.querySelectorAll('.browse-btn').forEach(btn => {
    if (!canBrowse) { btn.classList.add('hidden'); return; }
    btn.addEventListener('click', () => browseFile(btn.dataset.field, btn.dataset.type));
  });

  // File input modal
  openConfirmBtn.addEventListener('click', loadFromFileInputs);
  openCancelBtn.addEventListener('click',  () => { openModal.hidden = true; });
  openModal.querySelector('.modal-backdrop').addEventListener('click', () => { openModal.hidden = true; });

  // Warn before leaving with unsaved changes
  window.addEventListener('beforeunload', e => {
    if (isDirty) { e.preventDefault(); e.returnValue = ''; }
  });
}

// === File I/O =========================================================

async function openProject() {
  if ('showDirectoryPicker' in window) {
    await openWithFSA();
  } else {
    openModal.hidden = false;
  }
}

async function openWithFSA() {
  try {
    dirHandle = await window.showDirectoryPicker({ mode: 'readwrite' });
    const [scenes, sessions, campaigns] = await Promise.all([
      readJsonFromDir(dirHandle, 'scenes.json'),
      readJsonFromDir(dirHandle, 'sessions.json'),
      readJsonFromDir(dirHandle, 'campaigns.json'),
    ]);
    editorScenes    = Array.isArray(scenes)    ? scenes    : [];
    editorSessions  = Array.isArray(sessions)  ? sessions  : [];
    editorCampaigns = Array.isArray(campaigns) ? campaigns : [];
    isDirty = false;
    renderAll();
    showStatus('Project loaded from folder.', 'success');
  } catch (e) {
    if (e.name !== 'AbortError') showStatus('Could not open folder: ' + e.message, 'error');
  }
}

async function loadFromFileInputs() {
  const results = await Promise.all([
    readFileInput(scenesFileInput),
    readFileInput(sessionsFileInput),
    readFileInput(campaignsFileInput),
  ]);
  if (results[0]) editorScenes    = results[0];
  if (results[1]) editorSessions  = results[1];
  if (results[2]) editorCampaigns = results[2];
  openModal.hidden = true;
  isDirty = false;
  renderAll();
  showStatus('Files loaded. Edit, then Save to download updated files.', 'info');
}

function readFileInput(input) {
  return new Promise(resolve => {
    const file = input.files[0];
    if (!file) return resolve(null);
    const reader = new FileReader();
    reader.onload = e => {
      try { resolve(JSON.parse(e.target.result)); }
      catch { showStatus('Invalid JSON in ' + file.name, 'error'); resolve(null); }
    };
    reader.readAsText(file);
  });
}

// Called by the manual Save button — always persists, shows feedback on the button.
async function saveProject() {
  if (dirHandle) {
    await saveWithFSA();
  } else {
    downloadAll();
    flashSaveBtn('Downloaded');
  }
  isDirty = false;
}

// Called automatically after every item save. With FSA: silent write.
// Without FSA: nothing — the manual Save button handles it for that path.
async function autoSave() {
  if (!dirHandle) return;
  await saveWithFSA();
}

async function saveWithFSA() {
  try {
    const perm = await dirHandle.queryPermission({ mode: 'readwrite' });
    if (perm !== 'granted') {
      const req = await dirHandle.requestPermission({ mode: 'readwrite' });
      if (req !== 'granted') throw new Error('Permission denied');
    }
    await Promise.all([
      writeJsonToDir(dirHandle, 'scenes.json',    editorScenes),
      writeJsonToDir(dirHandle, 'sessions.json',  editorSessions),
      writeJsonToDir(dirHandle, 'campaigns.json', editorCampaigns),
    ]);
    flashSaveBtn('Saved ✓');
  } catch (e) {
    showStatus('Write failed — downloading instead. ' + e.message, 'error');
    downloadAll();
  }
}

function flashSaveBtn(text) {
  const orig = saveBtn.textContent;
  saveBtn.textContent = text;
  setTimeout(() => { saveBtn.textContent = orig; }, 2000);
}

function downloadAll() {
  downloadJson('scenes.json',    editorScenes);
  downloadJson('sessions.json',  editorSessions);
  downloadJson('campaigns.json', editorCampaigns);
}

async function readJsonFromDir(dir, filename) {
  try {
    const fh   = await dir.getFileHandle(filename);
    const file = await fh.getFile();
    const text = await file.text();
    return JSON.parse(text);
  } catch (_) { return null; }
}

async function writeJsonToDir(dir, filename, data) {
  const fh       = await dir.getFileHandle(filename, { create: true });
  const writable = await fh.createWritable();
  await writable.write(JSON.stringify(data, null, 2));
  await writable.close();
}

function downloadJson(filename, data) {
  const a  = document.createElement('a');
  a.href   = 'data:application/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data, null, 2));
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

async function browseFile(fieldName, fileType) {
  const isImage = fileType === 'image';
  const types   = isImage
    ? [{ description: 'Images', accept: { 'image/*': ['.jpg', '.jpeg', '.png', '.webp', '.gif'] } }]
    : [{ description: 'Audio',  accept: { 'audio/*': ['.mp3', '.ogg', '.wav', '.m4a', '.flac'] } }];
  try {
    const [fh]   = await window.showOpenFilePicker({ types });
    const file   = await fh.getFile();
    const prefix = isImage ? 'assets/images/' : 'assets/audio/';
    const input  = sceneForm.querySelector('[name="' + fieldName + '"]');
    if (input) input.value = prefix + file.name;
  } catch (e) {
    if (e.name !== 'AbortError') showStatus('File browser error: ' + e.message, 'error');
  }
}

// === Tab Management ===================================================

function switchTab(tabName) {
  tabBtns.forEach(b  => b.classList.toggle('active', b.dataset.tab === tabName));
  tabPanels.forEach(p => p.hidden = p.id !== 'tab-' + tabName);
}

// === Render All =======================================================

function renderAll() {
  renderScenes();
  renderSessions();
  renderCampaigns();
  populateCampaignDropdown();
}

// === Scenes ===========================================================

function renderScenes() {
  scenesList.innerHTML = '';
  scenesEmpty.hidden   = editorScenes.length > 0;

  editorScenes.forEach((scene, i) => {
    const li = document.createElement('li');
    li.className = 'list-item';
    li.innerHTML =
      `<div class="list-item-body">` +
      `<div class="list-item-title">${escHtml(scene.title || scene.id || 'Untitled')}</div>` +
      `<div class="list-item-meta">${escHtml(scene.id)}` +
      (scene.image ? '' : ' · <em>no image</em>') +
      (scene.audio ? '' : ' · <em>no audio</em>') +
      `</div></div>`;
    li.addEventListener('click', () => openSceneEdit(i));
    scenesList.appendChild(li);
  });
}

function openSceneEdit(idx) {
  editingSceneIdx = idx;
  idAutoGenerated = idx === null; // auto-slug only for new scenes
  sceneEditHeading.textContent = idx === null ? 'New Scene' : 'Edit Scene';
  deleteSceneBtn.style.display = idx === null ? 'none' : '';

  // Highlight active item
  Array.from(scenesList.children).forEach((li, i) => li.classList.toggle('active', i === idx));

  const scene = idx !== null ? editorScenes[idx] : {};
  const f = sceneForm;
  f.querySelector('[name="title"]').value    = scene.title    || '';
  f.querySelector('[name="id"]').value       = scene.id       || '';
  f.querySelector('[name="image"]').value    = scene.image    || '';
  f.querySelector('[name="audio"]').value    = scene.audio    || '';
  f.querySelector('[name="notes"]').value    = scene.notes    || '';
  f.querySelector('[name="dmScript"]').value = scene.dmScript || '';
  f.querySelector('[name="loopAudio"]').checked = scene.loopAudio !== false;

  sceneEditPanel.hidden = false;
}

function saveScene() {
  const f = sceneForm;
  const id    = f.querySelector('[name="id"]').value.trim();
  const title = f.querySelector('[name="title"]').value.trim();

  if (!id) { showStatus('ID is required.', 'error'); return; }

  // Check for duplicate ID (excluding the item being edited)
  const duplicate = editorScenes.some((s, i) => s.id === id && i !== editingSceneIdx);
  if (duplicate) { showStatus('A scene with this ID already exists.', 'error'); return; }

  const scene = {
    id,
    title:     title                                          || '',
    image:     f.querySelector('[name="image"]').value.trim()|| '',
    audio:     f.querySelector('[name="audio"]').value.trim()|| '',
    notes:     f.querySelector('[name="notes"]').value.trim()|| '',
    dmScript:  f.querySelector('[name="dmScript"]').value.trim() || '',
    loopAudio: f.querySelector('[name="loopAudio"]').checked,
  };

  // Remove empty string fields to keep JSON clean
  if (!scene.image)    delete scene.image;
  if (!scene.audio)    delete scene.audio;
  if (!scene.notes)    delete scene.notes;
  if (!scene.dmScript) delete scene.dmScript;

  if (editingSceneIdx !== null) {
    const oldId = editorScenes[editingSceneIdx].id;
    editorScenes[editingSceneIdx] = scene;
    if (oldId !== id) showStatus('Scene ID changed — check session references.', 'info');
  } else {
    editorScenes.push(scene);
  }

  isDirty = true;
  sceneEditPanel.hidden = true;
  editingSceneIdx = null;
  renderScenes();
  autoSave();
}

function deleteScene() {
  if (editingSceneIdx === null) return;
  const scene = editorScenes[editingSceneIdx];
  const refs  = editorSessions.filter(s => s.scenes && s.scenes.includes(scene.id));
  const warn  = refs.length ? ` ${refs.length} session(s) reference this scene and will show a broken-ref warning.` : '';
  if (!confirm('Delete "' + (scene.title || scene.id) + '"?' + warn)) return;
  editorScenes.splice(editingSceneIdx, 1);
  isDirty = true;
  sceneEditPanel.hidden = true;
  editingSceneIdx = null;
  renderScenes();
  renderSessions();
  autoSave();
}

// === Sessions =========================================================

function renderSessions() {
  sessionsList.innerHTML = '';
  sessionsEmpty.hidden   = editorSessions.length > 0;

  editorSessions.forEach((session, i) => {
    const campaign   = editorCampaigns.find(c => c.id === session.campaignId);
    const sceneCount = Array.isArray(session.scenes) ? session.scenes.length : 0;
    const broken     = (session.scenes || []).filter(id => !editorScenes.find(s => s.id === id));

    const li = document.createElement('li');
    li.className = 'list-item';
    li.innerHTML =
      `<div class="list-item-body">` +
      `<div class="list-item-title">${escHtml(session.title || session.id || 'Untitled')}</div>` +
      `<div class="list-item-meta">` +
      (campaign ? escHtml(campaign.title) + ' · ' : '') +
      `${sceneCount} scene${sceneCount !== 1 ? 's' : ''}</div></div>` +
      (broken.length ? `<span class="warn-badge">⚠ ${broken.length} missing</span>` : '');
    li.addEventListener('click', () => openSessionEdit(i));
    sessionsList.appendChild(li);
  });
}

function openSessionEdit(idx) {
  editingSessionIdx  = idx;
  idAutoGenerated    = idx === null;
  sessionEditHeading.textContent = idx === null ? 'New Session' : 'Edit Session';
  deleteSessionBtn.style.display = idx === null ? 'none' : '';

  Array.from(sessionsList.children).forEach((li, i) => li.classList.toggle('active', i === idx));

  const session = idx !== null ? editorSessions[idx] : {};
  const f = sessionForm;
  f.querySelector('[name="title"]').value = session.title || '';
  f.querySelector('[name="id"]').value    = session.id    || '';

  populateCampaignDropdown();
  sessionCampaignSelect.value = session.campaignId || '';

  editingSessionScenes = Array.isArray(session.scenes) ? [...session.scenes] : [];
  renderSessionSceneList();
  populateAddSceneDropdown();

  sessionEditPanel.hidden = false;
}

function saveSession() {
  const f  = sessionForm;
  const id    = f.querySelector('[name="id"]').value.trim();
  const title = f.querySelector('[name="title"]').value.trim();
  if (!id) { showStatus('ID is required.', 'error'); return; }

  const duplicate = editorSessions.some((s, i) => s.id === id && i !== editingSessionIdx);
  if (duplicate) { showStatus('A session with this ID already exists.', 'error'); return; }

  const session = {
    id,
    title:      title || '',
    campaignId: sessionCampaignSelect.value || undefined,
    scenes:     [...editingSessionScenes],
  };
  if (!session.campaignId) delete session.campaignId;

  if (editingSessionIdx !== null) {
    editorSessions[editingSessionIdx] = session;
  } else {
    editorSessions.push(session);
  }

  isDirty = true;
  sessionEditPanel.hidden = true;
  editingSessionIdx = null;
  renderSessions();
  autoSave();
}

function deleteSession() {
  if (editingSessionIdx === null) return;
  const s = editorSessions[editingSessionIdx];
  if (!confirm('Delete session "' + (s.title || s.id) + '"?')) return;
  editorSessions.splice(editingSessionIdx, 1);
  isDirty = true;
  sessionEditPanel.hidden = true;
  editingSessionIdx = null;
  renderSessions();
  autoSave();
}

function renderSessionSceneList() {
  sessionSceneList.innerHTML = '';
  sessionSceneEmpty.hidden   = editingSessionScenes.length > 0;

  editingSessionScenes.forEach((sceneId, i) => {
    const scene = editorScenes.find(s => s.id === sceneId);
    const li    = document.createElement('li');
    li.className = 'session-scene-row';

    const titleEl = document.createElement('span');
    titleEl.className   = 'session-scene-title';
    titleEl.textContent = scene ? (scene.title || sceneId) : '⚠ ' + sceneId + ' (missing)';
    if (!scene) titleEl.style.color = '#804040';

    const idEl = document.createElement('span');
    idEl.className   = 'session-scene-id';
    idEl.textContent = sceneId;

    const upBtn = document.createElement('button');
    upBtn.className   = 'scene-order-btn';
    upBtn.title       = 'Move up';
    upBtn.textContent = '↑';
    upBtn.disabled    = i === 0;
    upBtn.addEventListener('click', () => moveScene(i, -1));

    const downBtn = document.createElement('button');
    downBtn.className   = 'scene-order-btn';
    downBtn.title       = 'Move down';
    downBtn.textContent = '↓';
    downBtn.disabled    = i === editingSessionScenes.length - 1;
    downBtn.addEventListener('click', () => moveScene(i, 1));

    const removeBtn = document.createElement('button');
    removeBtn.className   = 'scene-remove-btn';
    removeBtn.title       = 'Remove from session';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => removeSceneFromSession(i));

    li.append(titleEl, idEl, upBtn, downBtn, removeBtn);
    sessionSceneList.appendChild(li);
  });

  populateAddSceneDropdown();
}

function populateAddSceneDropdown() {
  addSceneSelect.innerHTML = '<option value="">— add a scene —</option>';
  editorScenes
    .filter(s => !editingSessionScenes.includes(s.id))
    .forEach(s => {
      const opt = document.createElement('option');
      opt.value       = s.id;
      opt.textContent = s.title || s.id;
      addSceneSelect.appendChild(opt);
    });
}

function addSceneToSession() {
  const id = addSceneSelect.value;
  if (!id) return;
  editingSessionScenes.push(id);
  renderSessionSceneList();
}

function removeSceneFromSession(idx) {
  editingSessionScenes.splice(idx, 1);
  renderSessionSceneList();
}

function moveScene(idx, dir) {
  const dest = idx + dir;
  if (dest < 0 || dest >= editingSessionScenes.length) return;
  [editingSessionScenes[idx], editingSessionScenes[dest]] = [editingSessionScenes[dest], editingSessionScenes[idx]];
  renderSessionSceneList();
}

// === Campaigns ========================================================

function renderCampaigns() {
  campaignsList.innerHTML = '';
  campaignsEmpty.hidden   = editorCampaigns.length > 0;

  editorCampaigns.forEach((campaign, i) => {
    const sessionCount = editorSessions.filter(s => s.campaignId === campaign.id).length;
    const li = document.createElement('li');
    li.className = 'list-item';
    li.innerHTML =
      `<div class="list-item-body">` +
      `<div class="list-item-title">${escHtml(campaign.title || campaign.id || 'Untitled')}</div>` +
      `<div class="list-item-meta">${sessionCount} session${sessionCount !== 1 ? 's' : ''}` +
      (campaign.description ? ' · ' + escHtml(campaign.description) : '') +
      `</div></div>`;
    li.addEventListener('click', () => openCampaignEdit(i));
    campaignsList.appendChild(li);
  });

  populateCampaignDropdown();
}

function populateCampaignDropdown() {
  const current = sessionCampaignSelect ? sessionCampaignSelect.value : '';
  if (!sessionCampaignSelect) return;
  sessionCampaignSelect.innerHTML = '<option value="">(none)</option>';
  editorCampaigns.forEach(c => {
    const opt = document.createElement('option');
    opt.value       = c.id;
    opt.textContent = c.title || c.id;
    sessionCampaignSelect.appendChild(opt);
  });
  sessionCampaignSelect.value = current;
}

function openCampaignEdit(idx) {
  editingCampaignIdx = idx;
  idAutoGenerated    = idx === null;
  campaignEditHeading.textContent = idx === null ? 'New Campaign' : 'Edit Campaign';
  deleteCampaignBtn.style.display = idx === null ? 'none' : '';

  Array.from(campaignsList.children).forEach((li, i) => li.classList.toggle('active', i === idx));

  const campaign = idx !== null ? editorCampaigns[idx] : {};
  const f = campaignForm;
  f.querySelector('[name="title"]').value       = campaign.title       || '';
  f.querySelector('[name="id"]').value          = campaign.id          || '';
  f.querySelector('[name="description"]').value = campaign.description || '';

  campaignEditPanel.hidden = false;
}

function saveCampaign() {
  const f  = campaignForm;
  const id    = f.querySelector('[name="id"]').value.trim();
  const title = f.querySelector('[name="title"]').value.trim();
  if (!id) { showStatus('ID is required.', 'error'); return; }

  const duplicate = editorCampaigns.some((c, i) => c.id === id && i !== editingCampaignIdx);
  if (duplicate) { showStatus('A campaign with this ID already exists.', 'error'); return; }

  const campaign = {
    id,
    title:       title || '',
    description: f.querySelector('[name="description"]').value.trim() || '',
  };
  if (!campaign.description) delete campaign.description;

  if (editingCampaignIdx !== null) {
    editorCampaigns[editingCampaignIdx] = campaign;
  } else {
    editorCampaigns.push(campaign);
  }

  isDirty = true;
  campaignEditPanel.hidden = true;
  editingCampaignIdx = null;
  renderCampaigns();
  autoSave();
}

function deleteCampaign() {
  if (editingCampaignIdx === null) return;
  const c    = editorCampaigns[editingCampaignIdx];
  const refs = editorSessions.filter(s => s.campaignId === c.id);
  const warn = refs.length ? ` ${refs.length} session(s) belong to this campaign and will lose their campaign link.` : '';
  if (!confirm('Delete campaign "' + (c.title || c.id) + '"?' + warn)) return;
  editorCampaigns.splice(editingCampaignIdx, 1);
  isDirty = true;
  campaignEditPanel.hidden = true;
  editingCampaignIdx = null;
  renderCampaigns();
  renderSessions();
  autoSave();
}

// === Helpers ==========================================================

function slugify(text) {
  return text.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/[\s]+/g, '-')
    .replace(/-+/g, '-');
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

let statusTimer = null;
function showStatus(msg, type) {
  statusBar.textContent = msg;
  statusBar.className   = type;
  statusBar.hidden      = false;
  clearTimeout(statusTimer);
  statusTimer = setTimeout(() => { statusBar.hidden = true; }, 4000);
}

// === Start ============================================================
init();
